Fix future compilation of 2023-09-21-dalamud-v9-stabilization.md
Add closing tag to <br> as v3 will throw an error on unclosed statements
- Error: MDX compilation failed for file
- Cause: Expected a closing tag for `<br>` (51:1-51:5)